### ISSUE TITLE
Mule 3 Until Successful: Failed to increment failure count for event stored with key

### ISSUE THREAD

**Issue by atheedom** [mulesoft-consulting/mule4-core-component-migration-blog#7]
I copy and pasted the code from GitHub added a listener to the until-successful example and on invoking the listener endpoint the following exception was thrown.

Link to Mule Config: https://github.com/mulesoft-consulting/mule4-core-component-migration-blog/blob/master/mule3-core-components/src/main/app/mule3-until-successful.xml

ERROR 2019-10-21 22:48:00,568 [[mule3-until-successful-scope].until-successful-example.until-successful.01] org.mule.routing.AsynchronousUntilSuccessfulProcessingStrategy: Failed to increment failure count for event stored with key: QueueKey@1191163565 queueName=queuestore id=Flow{until-successful-example}--0-653673b0-f44c-11e9-ace8-645d8688fef9-184791910
org.mule.api.store.ObjectStoreException: Deleting C:\Users\atheedom\Documents\Anypoint Studio\blog-posts\.mule\.mule\mule3-until-successful-scope\objectstore\328ab3d0-ef25-11e9-891a-645d8688fef9\6c6d6030-f44c-11e9-ace8-645d8688fef9.obj failed
	at org.mule.util.store.PersistentObjectStorePartition.deleteStoreFile(PersistentObjectStorePartition.java:489) ~[mule-core-3.9.3.jar:3.9.3]
	at org.mule.util.store.PersistentObjectStorePartition.remove(PersistentObjectStorePartition.java:209) ~[mule-core-3.9.3.jar:3.9.3]
	at org.mule.util.store.PartitionedPersistentObjectStore.remove(PartitionedPersistentObjectStore.java:129) ~[mule-core-3.9.3.jar:3.9.3]
	at org.mule.util.store.AbstractPartitionedObjectStore.remove(AbstractPartitionedObjectStore.java:63) ~[mule-core-3.9.3.jar:3.9.3]
	at org.mule.routing.AsynchronousUntilSuccessfulProcessingStrategy.incrementProcessAttemptCountAndRescheduleOrRemoveFromStore(AsynchronousUntilSuccessfulProcessingStrategy.java:235) ~[mule-core-3.9.3.jar:3.9.3]
	at org.mule.routing.AsynchronousUntilSuccessfulProcessingStrategy.access$400(AsynchronousUntilSuccessfulProcessingStrategy.java:63) ~[mule-core-3.9.3.jar:3.9.3]
	at org.mule.routing.AsynchronousUntilSuccessfulProcessingStrategy$3.run(AsynchronousUntilSuccessfulProcessingStrategy.java:225) ~[mule-core-3.9.3.jar:3.9.3]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_191]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]

**Comment by atheedom** [comment]
I am using Studio 6.6.3.

**Comment by GitUser-SG** [comment]
Did you get a solution , I am having the same issue with Batch processing. It just can't start Processing Records after input phase and fails with exact same error.  I have also upgraded to Studio 6.6.3.
